fix: adjusted the code order and modified the API with strikethrough in /ContestSite
eesast/web pull request #1559
Opened 2024-02-01 13:40 UTC by youyc22

2024-02-04 05:08 UTC, FranGuam requested changes
LoginPage 需要 revert

2024-02-04 05:08 UTC, FranGuam commented on src/app/UserSite/LoginPage.tsx
LoginPage 的临时改动不用提交，改动前的才是适配api新版本的

2024-02-06 14:13 UTC, youyc22 commented on src/app/UserSite/LoginPage.tsx
已经改回去了

2024-02-07 03:33 UTC, FranGuam approved these changes
All Clear. @xiangmy21

2024-02-09 10:06 UTC, merged