fix: revise team_leader to team_leader_uuid
eesast/web pull request #1643
Opened 2024-03-10 13:19 UTC by youyc22

2024-03-10 16:07 UTC, FranGuam requested changes
一点小建议

2024-03-10 16:07 UTC, FranGuam commented on src/app/ContestSite/JoinPage.tsx
调试用的输出建议删除

2024-03-10 16:56 UTC, xiangmy21 submitted a review, later dismissed

2024-03-11 01:36 UTC, youyc22 commented on src/app/ContestSite/JoinPage.tsx
哦哦，忘记了

2024-03-11 02:42 UTC, FranGuam approved these changes

2024-03-11 02:46 UTC, merged