Update docs/code.md
eesast/web pull request #1684
Opened 2024-03-25 09:09 UTC by zzdhybthu

Contribute: 
1. Add CODE_ID and LANG environment variable passed to the compiled container.
2. Update description of error codes and route parameters
3. Change .log to .txt momentarily, which caters to the preferences of the team development team.

2024-03-25 10:04 UTC, FranGuam requested changes

2024-03-25 10:04 UTC, FranGuam commented on docs/code.md
> +2. `docker`启动时代码文件绑定在`/usr/local/code`文件夹下，编译产生的可执行文件和`log`同样保存到`/usr/local/code`文件夹（命名与代码文件前缀相同）
这边绑定两个文件夹会有什么困难吗？之前改成两个文件夹主要是可拓展性的考虑

2024-03-25 10:04 UTC, FranGuam commented on docs/code.md
> +3. `docker`启动时会设置环境变量`URL`，`TOKEN`，`CODE_ID`，`LANG`（目前默认是 `cpp`），编译完成后需要请求`URL`（实际上是`/code/compile-finish`），请求时需要在`header`中加上`TOKEN`，请求的`body`中需包括代码编译的状态`compile_status: string`，取值为`Success`或`Failed`
这边`CODE_ID`的环境变量似乎不必要，`TOKEN`中已经包含了`code_id`

2024-03-25 10:07 UTC, FranGuam commented
另外`CI`没跑通是偶发性的，`rerun`一下就好了

2024-03-25 10:09 UTC, zzdhybthu commented on docs/code.md
> +3. `docker`启动时会设置环境变量`URL`，`TOKEN`，`CODE_ID`，`LANG`（目前默认是 `cpp`），编译完成后需要请求`URL`（实际上是`/code/compile-finish`），请求时需要在`header`中加上`TOKEN`，请求的`body`中需包括代码编译的状态`compile_status: string`，取值为`Success`或`Failed`
这个之前问了mygg，他说env里设一个codeid，免得docker里面再加包了（）

2024-03-25 10:10 UTC, zzdhybthu commented on docs/code.md
> +2. `docker`启动时代码文件绑定在`/usr/local/code`文件夹下，编译产生的可执行文件和`log`同样保存到`/usr/local/code`文件夹（命名与代码文件前缀相同）
如果绑定docker的 output 文件夹到主机的team_id文件夹，docker的 output 文件夹里也会有codeid_suffix文件。这样一来容器里code和output文件夹里都会有codeid_suffix，分文件貌似就没有意义了。

2024-03-25 10:12 UTC, zzdhybthu commented on docs/code.md
> +  - 请求：`body`中有`{contest_name: string, code_id: uuid, language: string}`，其中`contest_name`是数据库中的`name`、用于确定用于编译的镜像，`code_id`用于更改数据库，`language`为编程语言（增加其他语言前固定为`cpp`，不用管）
好的。cos文件的结构用path传进去，docker 服务器的路径用code_id拼出来，是这样吗？

2024-03-25 10:17 UTC, FranGuam commented on docs/code.md
> +  - 请求：`body`中有`{contest_name: string, code_id: uuid, language: string}`，其中`contest_name`是数据库中的`name`、用于确定用于编译的镜像，`code_id`用于更改数据库，`language`为编程语言（增加其他语言前固定为`cpp`，不用管）
> docker 服务器的路径用code_id拼出来

docker 服务器的路径你指的是什么

2024-03-25 10:23 UTC, FranGuam commented on docs/code.md
> +2. `docker`启动时代码文件绑定在`/usr/local/code`文件夹下，编译产生的可执行文件和`log`同样保存到`/usr/local/code`文件夹（命名与代码文件前缀相同）
目前来看的确没有意义，但是如果未来希望代码和输出不在同一个文件夹（例如代码下载到后端服务器即刻删除、可执行文件放到与赛事服务器共享的文件夹），那么在队式不动的前提下后端就需要多写几行移动文件的代码。我说的“可拓展性”是这个意思。当然，在这个案例中，切换成本很低，的确无关紧要。

2024-03-25 10:24 UTC, FranGuam commented on docs/code.md
> +3. `docker`启动时会设置环境变量`URL`，`TOKEN`，`CODE_ID`，`LANG`（目前默认是 `cpp`），编译完成后需要请求`URL`（实际上是`/code/compile-finish`），请求时需要在`header`中加上`TOKEN`，请求的`body`中需包括代码编译的状态`compile_status: string`，取值为`Success`或`Failed`
“加包”？什么意思？是不用`TOKEN`了吗

2024-03-25 10:29 UTC, xiangmy21 commented on docs/code.md
> +3. `docker`启动时会设置环境变量`URL`，`TOKEN`，`CODE_ID`，`LANG`（目前默认是 `cpp`），编译完成后需要请求`URL`（实际上是`/code/compile-finish`），请求时需要在`header`中加上`TOKEN`，请求的`body`中需包括代码编译的状态`compile_status: string`，取值为`Success`或`Failed`
我的意思是现在docker里应该没写解析token的代码，可以传个FILENAME让它好处理

2024-03-25 10:32 UTC, FranGuam commented on docs/code.md
> +  - 错误：
对了，这边返回状态码其实不是很本质，因为只有`docker`会请求这个路由，返回任何状态都不会处理。不过保留着没啥问题，代码写简洁一点就行，当成内部方法（

2024-03-25 10:52 UTC, zzdhybthu commented on docs/code.md
> +  - 请求：`body`中有`{contest_name: string, code_id: uuid, language: string}`，其中`contest_name`是数据库中的`name`、用于确定用于编译的镜像，`code_id`用于更改数据库，`language`为编程语言（增加其他语言前固定为`cpp`，不用管）
就是跑docker的服务器和后端服务器的文件存储路径

2024-03-25 10:54 UTC, zzdhybthu commented on docs/code.md
> +  - 请求：`body`中有`{contest_name: string, code_id: uuid, language: string}`，其中`contest_name`是数据库中的`name`、用于确定用于编译的镜像，`code_id`用于更改数据库，`language`为编程语言（增加其他语言前固定为`cpp`，不用管）
传 Path的话compiler-finish路由也得传一下，放在 token 里？compiler-finish需要往cos上传可执行文件和log

2024-03-25 10:55 UTC, zzdhybthu commented on docs/code.md
> +2. `docker`启动时代码文件绑定在`/usr/local/code`文件夹下，编译产生的可执行文件和`log`同样保存到`/usr/local/code`文件夹（命名与代码文件前缀相同）
OK

2024-03-25 10:56 UTC, zzdhybthu commented on docs/code.md
> +  - 错误：
好的

2024-03-25 10:57 UTC, BlitherBoom812 commented on docs/code.md
> +  - 请求：`body`中有`{contest_name: string, code_id: uuid, language: string}`，其中`contest_name`是数据库中的`name`、用于确定用于编译的镜像，`code_id`用于更改数据库，`language`为编程语言（增加其他语言前固定为`cpp`，不用管）
感觉从 cos 下载到后端这个路径和文件名可以自己设定？也可以在code.md里面报告一下，不过应该不涉及接口的问题，因为只是给后端看的

2024-03-25 11:15 UTC, BlitherBoom812 commented on docs/code.md
> +2. `docker`启动时代码文件绑定在`/usr/local/code`文件夹下，编译产生的可执行文件和`log`同样保存到`/usr/local/code`文件夹（命名与代码文件前缀相同）
> 目前来看的确没有意义，但是如果未来希望代码和输出不在同一个文件夹（例如代码下载到后端服务器即刻删除、可执行文件放到与赛事服务器共享的文件夹），那么在队式不动的前提下后端就需要多写几行移动文件的代码。我说的“可拓展性”是这个意思。当然，在这个案例中，切换成本很低，的确无关紧要。

感觉实际上这两个都要放在共享文件夹里，编译的时候需要共享代码，比赛的时候需要共享可执行文件？而且对于python而言代码就是可执行文件。
不过我支持分两个文件夹。如果这样的话建议 cos 也统一，上传到 cos 的时候 code 和 output 分别占两个文件夹。比赛的时候只要把 output 中的文件下载下来就可以了。

2024-03-25 11:18 UTC, BlitherBoom812 commented on docs/code.md
> +3. `docker`启动时会设置环境变量`URL`，`TOKEN`，`CODE_ID`，`LANG`（目前默认是 `cpp`），编译完成后需要请求`URL`（实际上是`/code/compile-finish`），请求时需要在`header`中加上`TOKEN`，请求的`body`中需包括代码编译的状态`compile_status: string`，取值为`Success`或`Failed`
docker 为啥要解析 token，不是编译完回传就可以了吗

2024-03-25 11:31 UTC, zzdhybthu commented on docs/code.md
> +3. `docker`启动时会设置环境变量`URL`，`TOKEN`，`CODE_ID`，`LANG`（目前默认是 `cpp`），编译完成后需要请求`URL`（实际上是`/code/compile-finish`），请求时需要在`header`中加上`TOKEN`，请求的`body`中需包括代码编译的状态`compile_status: string`，取值为`Success`或`Failed`
因为要确定需要编译的文件名，同一组的用户短时间内集中上传代码时会有多份需要编译的文件在同一个绑定到 docker 的文件夹内，每个容器需要知道自己负责编译哪份代码。现在的做法是传环境变量告诉 docker 文件名，另一种做法是解析 token 得到文件名

2024-03-25 11:54 UTC, zzdhybthu commented on docs/code.md
> +2. `docker`启动时代码文件绑定在`/usr/local/code`文件夹下，编译产生的可执行文件和`log`同样保存到`/usr/local/code`文件夹（命名与代码文件前缀相同）
确实，cos, docker, server的目录结构都统一改一下方便操作。不过不改应该也没什么大问题（）

2024-03-25 11:57 UTC, BlitherBoom812 commented on docs/code.md
> +3. `docker`启动时会设置环境变量`URL`，`TOKEN`，`CODE_ID`，`LANG`（目前默认是 `cpp`），编译完成后需要请求`URL`（实际上是`/code/compile-finish`），请求时需要在`header`中加上`TOKEN`，请求的`body`中需包括代码编译的状态`compile_status: string`，取值为`Success`或`Failed`
感觉代码名称交给 docker 判断，又出现耦合了，不应该是我们绑定的时候，一个 docker 的文件夹下只有一份代码吗？如果考虑到可扩展性，假设以后一个 docker 可以编译多份代码，那传进去的 path 就要是一个列表，然后又需要 docker 具有判断列表的能力。可不可以给每个 code 建立一个文件夹（名字就是code id）？

2024-03-25 12:38 UTC, FranGuam reviewed
先别急着改，看看大家的意见 @BlitherBoom812 @xiangmy21

2024-03-25 12:38 UTC, FranGuam commented on docs/code.md
> +  - 请求：`body`中有`{contest_name: string, code_id: uuid, language: string, path: string}`，其中`contest_name`是数据库中的`name`、用于确定用于编译的镜像，`code_id`用于更改数据库，`language`为编程语言（增加其他语言前固定为`cpp`，不用管），`path` 为可选参数，用于指定
如果后端通过查数据库拼路径的话，这边其实改成只传`{code_id: uuid}`更好，其他几个数据都是依赖于`code_id`的。`contest_name`用请求里给的而`team_id`用查数据库的混合起来感觉有点怪怪的

2024-03-25 12:38 UTC, FranGuam commented on docs/code.md
> +  - 请求：`body`中有`{compile_status: string}`，`token`中有`{team_id: uuid, code_id: uuid, contest_name: string, cos_path: string}`（启动`docker`时传入）
这边可以相应改成`{code_id: uuid, compile_status: string}`，不传`token`

2024-03-25 12:38 UTC, FranGuam commented on docs/code.md
> +3. `docker`启动时会设置环境变量`URL`，`TOKEN`，`CODE_ID`，`LANG`（目前默认是 `cpp`），编译完成后需要请求`URL`（实际上是`/code/compile-finish`），请求时需要在`header`中加上`TOKEN`，请求的`body`中需包括代码编译的状态`compile_status: string`，取值为`Success`或`Failed`
这边的环境变量相应改成`URL`，`CODE_ID`，`LANG`

2024-03-25 12:41 UTC, FranGuam commented on docs/code.md
> +3. `docker`启动时会设置环境变量`URL`，`TOKEN`，`CODE_ID`，`LANG`（目前默认是 `cpp`），编译完成后需要请求`URL`（实际上是`/code/compile-finish`），请求时需要在`header`中加上`TOKEN`，请求的`body`中需包括代码编译的状态`compile_status: string`，取值为`Success`或`Failed`
> 同一组的用户短时间内集中上传代码时会有多份需要编译的文件在同一个绑定到 docker 的文件夹内

这个情况不应存在，`docker`是串行地编译代码，理应起多个`docker`并行而非挂载到同一个`docker`。这样一份代码对应一个`docker`也方便管理，见“与赛事组的约定”第一条

2024-03-25 12:44 UTC, FranGuam commented on docs/code.md
> +3. `docker`启动时会设置环境变量`URL`，`TOKEN`，`CODE_ID`，`LANG`（目前默认是 `cpp`），编译完成后需要请求`URL`（实际上是`/code/compile-finish`），请求时需要在`header`中加上`TOKEN`，请求的`body`中需包括代码编译的状态`compile_status: string`，取值为`Success`或`Failed`
> 我的意思是现在docker里应该没写解析token的代码，可以传个FILENAME让它好处理

`docker`里已经写了提取`filename`的语句。不过我认为传`token`确实没太大必要，为了安全性的话反而是`/code/compile-start`能不能用中间件限制为仅部分ip访问？

2024-03-25 12:46 UTC, BlitherBoom812 commented on docs/code.md
> +3. `docker`启动时会设置环境变量`URL`，`TOKEN`，`CODE_ID`，`LANG`（目前默认是 `cpp`），编译完成后需要请求`URL`（实际上是`/code/compile-finish`），请求时需要在`header`中加上`TOKEN`，请求的`body`中需包括代码编译的状态`compile_status: string`，取值为`Success`或`Failed`
等等，就是说现在技术路线要改吗？现在不用 token 了？然后改成检查 ip？但是检查 ip 这个东西真的比 token 安全吗（

2024-03-25 12:50 UTC, FranGuam commented on docs/code.md
> +3. `docker`启动时会设置环境变量`URL`，`TOKEN`，`CODE_ID`，`LANG`（目前默认是 `cpp`），编译完成后需要请求`URL`（实际上是`/code/compile-finish`），请求时需要在`header`中加上`TOKEN`，请求的`body`中需包括代码编译的状态`compile_status: string`，取值为`Success`或`Failed`
> 因为要确定需要编译的文件名，同一组的用户短时间内集中上传代码时会有多份需要编译的文件在同一个绑定到 docker 的文件夹内，每个容器需要知道自己负责编译哪份代码。现在的做法是传环境变量告诉 docker 文件名，另一种做法是解析 token 得到文件名

> 感觉代码名称交给 docker 判断，又出现耦合了，不应该是我们绑定的时候，一个 docker 的文件夹下只有一份代码吗？如果考虑到可扩展性，假设以后一个 docker 可以编译多份代码，那传进去的 path 就要是一个列表，然后又需要 docker 具有判断列表的能力。可不可以给每个 code 建立一个文件夹（名字就是code id）？

这个问题我的确忘记考虑了。不过这个耦合相对好解决，在接口文档里规定好让队式的编译`docker`根据我们给的环境变量直接拼路径就行。单独建文件夹的确是另一种解决方案，不过可能后端写起来烦一点。

2024-03-25 12:53 UTC, FranGuam commented on docs/code.md
> +3. `docker`启动时会设置环境变量`URL`，`TOKEN`，`CODE_ID`，`LANG`（目前默认是 `cpp`），编译完成后需要请求`URL`（实际上是`/code/compile-finish`），请求时需要在`header`中加上`TOKEN`，请求的`body`中需包括代码编译的状态`compile_status: string`，取值为`Success`或`Failed`
> 等等，就是说现在技术路线要改吗？现在不用 token 了？然后改成检查 ip？但是检查 ip 这个东西真的比 token 安全吗（

这……就涉及到我的知识盲区了。公网ip能伪装吗

2024-03-25 12:54 UTC, FranGuam commented on docs/code.md
> +3. `docker`启动时会设置环境变量`URL`，`TOKEN`，`CODE_ID`，`LANG`（目前默认是 `cpp`），编译完成后需要请求`URL`（实际上是`/code/compile-finish`），请求时需要在`header`中加上`TOKEN`，请求的`body`中需包括代码编译的状态`compile_status: string`，取值为`Success`或`Failed`
或者这样问吧，后端写每个代码一个临时文件夹代码量大吗

2024-03-25 13:32 UTC, zzdhybthu commented on docs/code.md
> +3. `docker`启动时会设置环境变量`URL`，`TOKEN`，`CODE_ID`，`LANG`（目前默认是 `cpp`），编译完成后需要请求`URL`（实际上是`/code/compile-finish`），请求时需要在`header`中加上`TOKEN`，请求的`body`中需包括代码编译的状态`compile_status: string`，取值为`Success`或`Failed`
要不先把这个 PR 给过了，然后你们达成一致后对这个文档进行修改，我根据这个文档改后端代码？

2024-03-25 17:46 UTC, FranGuam commented on docs/code.md
> +3. `docker`启动时会设置环境变量`URL`，`TOKEN`，`CODE_ID`，`LANG`（目前默认是 `cpp`），编译完成后需要请求`URL`（实际上是`/code/compile-finish`），请求时需要在`header`中加上`TOKEN`，请求的`body`中需包括代码编译的状态`compile_status: string`，取值为`Success`或`Failed`
PR先放着，明天我们沟通一下

2024-03-26 17:33 UTC, FranGuam approved these changes
已经统一啦~ @zzdhybthu

2024-03-26 17:33 UTC, merged