fix: revise tour error and integrate codes in ManagerPage
eesast/web pull request #1696
Opened 2024-03-31 13:59 UTC by youyc22

1. 导览结束选项说明要跳转到试玩、导览第一项名称改变
2. 管理员页面基本框架完成

2024-03-31 16:40 UTC, FranGuam requested changes
如果分模块写tsx文件的话不建议以Page后缀命名，而应该当成Component放进子文件夹

2024-03-31 16:42 UTC, FranGuam commented
这个PR不急着merge，等相对完善后再提，你觉得如何？

2024-04-01 01:17 UTC, youyc22 commented
> 这个PR不急着merge，等相对完善后再提，你觉得如何？
好的

2024-04-02 04:00 UTC, FranGuam commented
moment已经不在维护了噢（https://www.npmjs.com/package/moment），如果显示日期的话可以参考其他页面使用dayjs

2024-04-02 16:43 UTC, youyc22 commented
> moment已经不在维护了噢（[moment | npm](https://www.npmjs.com/package/moment)），如果显示日期的话可以参考其他页面使用[dayjs](https://ant.design/docs/react/use-custom-date-library-cn)

已经改了，我刚在settingPage重写了发起比赛的逻辑，不知道对不对

2024-04-03 01:04 UTC, FranGuam requested changes
进展不错，加油！

2024-04-03 01:04 UTC, FranGuam commented on src/app/ContestSite/ManagerPage/SettingPage.tsx
> +            试玩模式
改为“试玩功能”

2024-04-03 01:04 UTC, FranGuam commented on src/app/ContestSite/ManagerPage/SettingPage.tsx
> +            直播模式
同上

2024-04-03 01:04 UTC, FranGuam commented on src/app/ContestSite/ManagerPage/SettingPage.tsx
> +            回放模式
同上

2024-04-03 01:04 UTC, FranGuam commented on src/app/ContestSite/ManagerPage/SettingPage.tsx
> +          </Form.Item>
相应更改

2024-04-03 01:04 UTC, FranGuam commented on src/app/ContestSite/ManagerPage/SettingPage.tsx
> +      }
建议使用`Authenticate`组件，见`src/app/Components`

2024-04-03 01:04 UTC, FranGuam commented on src/app/ContestSite/MenuPage.tsx
>        icon: <LockOutlined />,
用`<SettingOutlined />`吧，感觉好看一点（

2024-04-03 01:04 UTC, FranGuam commented on src/app/ContestSite/PlaybackPage.tsx
> +  console.log(contestSwitchData);
调试语句记得删除

2024-04-03 13:25 UTC, youyc22 commented on src/app/ContestSite/ManagerPage/SettingPage.tsx
> +      }
> 建议使用`Authenticate`组件，见`src/app/Components`

意思是在外面套一个Authenticate组件吗

2024-04-03 13:37 UTC, youyc22 commented
> 进展不错，加油！

AddContestRound那个接口里有个maps，是不是应该改成map_id，数据库里好像没有maps里这一栏

2024-04-04 06:36 UTC, FranGuam commented
> > 进展不错，加油！
> 
> AddContestRound那个接口里有个maps，是不是应该改成map_id，数据库里好像没有maps里这一栏

是的，这是我昨天上午改的，为了避免歧义，graphql语句已改（master分支）。

2024-04-07 11:00 UTC, FranGuam requested changes

2024-04-07 11:00 UTC, FranGuam commented on src/graphql/contest/index.graphql
> +    team_switch
上面已经有`team_switch`了

2024-04-07 11:00 UTC, FranGuam commented on src/graphql/contest/index.graphql
> +    team_switch
弄完记得重新`yarn generate`

2024-04-07 11:00 UTC, FranGuam commented on src/app/ContestSite/PlaygroundPage.tsx
>    const projectName = "Playground";
这边改成`playground`小写，与`cos`上统一

2024-04-07 11:00 UTC, FranGuam commented on src/app/ContestSite/PlaygroundPage.tsx
> +    </Layout>
`<ReactRouterPrompt>`是需要复制过来的，否则会导致直接点击其他页面后WebGL未退出而报错

2024-04-07 11:00 UTC, FranGuam commented on src/app/ContestSite/PlaybackPage.tsx
>        message.error("获取队伍列表失败");
下面也相应改成`playback`，小写

2024-04-07 11:00 UTC, FranGuam commented
加油！剩下就是小修小补，有希望马上merge

2024-04-07 11:10 UTC, youyc22 commented on src/app/ContestSite/PlaygroundPage.tsx
>    const projectName = "Playground";
> 这边改成`playground`小写，与`cos`上统一

怪不得我打不开（

2024-04-07 11:12 UTC, FranGuam commented on src/app/ContestSite/PlaygroundPage.tsx
>    const projectName = "Playground";
楽

2024-04-07 11:12 UTC, FranGuam commented on src/app/ContestSite/PlaygroundPage.tsx
>    const projectName = "Playground";
这是我的锅，一开始想当然给大写了，传`cos`时才觉得文件名小写比较合适

2024-04-07 11:25 UTC, FranGuam commented on src/app/ContestSite/PlaygroundPage.tsx
>      // TODO: Copy from PlaybackPage.tsx
TODO记得删掉

2024-04-07 11:26 UTC, FranGuam approved these changes

2024-04-07 11:31 UTC, FranGuam approved these changes

2024-04-07 11:33 UTC, merged