chore(docs): update contest.md
eesast/web pull request #1700
Opened 2024-04-01 06:36 UTC by FranGuam

2024-04-01 09:34 UTC, xiangmy21 commented on docs/contest.md
> +   - 后端也要检查数据库上的代码编译状态和角色代码分配状态，都正常的情况下再继续下一步。
这么写也可以，另一种方式是后端检查然后返回错误码给前端，前端根据错误信息来报错。你觉得哪种合适

2024-04-01 09:49 UTC, FranGuam commented on docs/contest.md
> +   - 后端也要检查数据库上的代码编译状态和角色代码分配状态，都正常的情况下再继续下一步。
我觉得都得做，前端先拦掉一些不合法的请求，后端报错前端也会处理。不过前端的提示不本质，后端肯定还是要检查的

2024-04-01 10:10 UTC, xiangmy21 requested changes

2024-04-01 10:10 UTC, xiangmy21 commented on docs/contest.md
> +  - 请求：`{result: ContestResult[]}` ，类型定义见下方附录。同时在`headers`里传回创建`docker`时设置的`docker`。
“创建docker时设置的TOKEN”

2024-04-01 10:10 UTC, xiangmy21 commented on docs/contest.md
> +1. 一场比赛对应两个`docker`镜像、多个`docker`并行。其中`server`镜像为比赛逻辑服务器，`client`镜像为选手代码执行客户端（一队共用）。
这个确定了吗？client是一队还是两队啊

2024-04-01 10:10 UTC, xiangmy21 commented on docs/contest.md
> +2. 队式应当关注上面的`/arena/finish`和`/competition/finish`路由参数信息。`server`镜像启动时会设置环境变量`URL`（即`/arena/finish`或`/competition/finish`）和`TOKEN`，比赛结束后需要请求`URL`，请求时需要在`headers`中加上`TOKEN`，在`body`中加上每个队的分数`result`。`cl
`client`，字打错了

2024-04-01 10:10 UTC, xiangmy21 commented on docs/contest.md
> +2. 队式应当关注上面的`/arena/finish`和`/competition/finish`路由参数信息。`server`镜像启动时会设置环境变量`URL`（即`/arena/finish`或`/competition/finish`）和`TOKEN`，比赛结束后需要请求`URL`，请求时需要在`headers`中加上`TOKEN`，在`body`中加上每个队的分数`result`。`cl
这个LABEL是后端根据TeamLabels设置？有什么用吗

2024-04-01 11:16 UTC, FranGuam commented on docs/contest.md
> +  - 请求：`{result: ContestResult[]}` ，类型定义见下方附录。同时在`headers`里传回创建`docker`时设置的`docker`。
老眼昏花了（

2024-04-01 11:17 UTC, FranGuam commented on docs/contest.md
> +1. 一场比赛对应两个`docker`镜像、多个`docker`并行。其中`server`镜像为比赛逻辑服务器，`client`镜像为选手代码执行客户端（一队共用）。
一个队伍对应一个client，但client用的镜像都是同一个。 @DragonAura 是这么跟我说的，看看他的意见

2024-04-01 11:19 UTC, FranGuam commented on docs/contest.md
> +2. 队式应当关注上面的`/arena/finish`和`/competition/finish`路由参数信息。`server`镜像启动时会设置环境变量`URL`（即`/arena/finish`或`/competition/finish`）和`TOKEN`，比赛结束后需要请求`URL`，请求时需要在`headers`中加上`TOKEN`，在`body`中加上每个队的分数`result`。`cl
> 这个LABEL是后端根据TeamLabels设置？有什么用吗

这我的确不太确定。但不然docker怎么区分不同队伍呢（不对称情况下）？还是看李圣怎么说吧，这边主要是他们需要什么参数传什么

2024-04-01 13:47 UTC, FranGuam commented
@zzdhybthu 也来看看实现起来有什么要改的地方吧

2024-04-01 15:02 UTC, FranGuam commented on docs/contest.md
> +2. 队式应当关注上面的`/arena/finish`和`/competition/finish`路由参数信息。`server`镜像启动时会设置环境变量`URL`（即`/arena/finish`或`/competition/finish`）和`TOKEN`，比赛结束后需要请求`URL`，请求时需要在`headers`中加上`TOKEN`，在`body`中加上每个队的分数`result`。`cl
此处已改，请看新版

2024-04-01 16:07 UTC, FranGuam commented on docs/contest.md
> +   - `server`镜像启动时会设置环境变量`URL`（即`/arena/finish`或`/competition/finish-one`）、`TOKEN`和`ARENA_SCORE`，比赛结束后需要请求`URL`，请求时需要在`headers`中加上`TOKEN`。`ARENA_SCORE`记录的是两队在天梯/比赛中的现有分数（类型定义见下方附录`ContestResult`），`do
此处已改，请看新版

2024-04-02 03:31 UTC, zzdhybthu commented on docs/contest.md
比赛服务器的可执行文件存储路径有规定吗？

2024-04-02 03:45 UTC, zzdhybthu commented on docs/contest.md
下载的可执行文件在服务器上保留多少合适？感觉是可以在每次发起对战的时候删除过时的文件，保留contest_code表里参赛队伍选中的文件以及若干个较新的文件。
此外为什么现在数据库contest_code表里的code是类似”THUAI6/code/7a3af771-ca71-4f7d-9813-13a1d5b364b8/player1.cpp“的形式，不应该是code_id吗

2024-04-02 03:47 UTC, FranGuam commented on docs/contest.md
> 比赛服务器的可执行文件存储路径有规定吗？

没有规定，不属于接口范畴

2024-04-02 03:49 UTC, BlitherBoom812 commented on docs/contest.md
contest_code 表现在没用了吧，现在的 code 路径是直接拼出来的？和之前 code.ts 的方式一致

2024-04-02 03:50 UTC, FranGuam commented on docs/contest.md
> 下载的可执行文件在服务器上保留多少合适？感觉是可以在每次发起对战的时候删除过时的文件，保留contest_code表里参赛队伍选中的文件以及若干个较新的文件。 此外为什么现在数据库contest_code表里的code是类似”THUAI6/code/7a3af771-ca71-4f7d-9813-13a1d5b364b8/player1.cpp“的形式，不应该是code_id吗

建议按照剩余容量设立阈值，从旧到新删除；
数据库中`contest_code`是计划要废除的表，代码情况应记录在`contest_team_code`和`contest_team_player`表中。

2024-04-02 03:53 UTC, zzdhybthu commented on docs/contest.md
哦哦 看到了

2024-04-02 03:55 UTC, zzdhybthu commented on docs/contest.md
好的，暂时想不出什么问题（）

2024-04-02 12:07 UTC, zzdhybthu commented on docs/contest.md
用 TeamLabelBind 里的队伍id检查发起比赛的人是否在队伍中的话，没法区分比赛的发起队伍和应战队伍，如果有人借此强迫其它队伍向自己的队伍发起挑战的话也能通过验证？

2024-04-02 14:55 UTC, xiangmy21 approved these changes

2024-04-02 14:55 UTC, merged