fix(docs): mistouch something
eesast/web pull request #1771
Opened 2024-04-28 12:22 UTC by BlitherBoom812

2024-04-28 15:55 UTC, xiangmy21 requested changes

2024-04-28 15:55 UTC, xiangmy21 commented on docs/contest.md
> +  - 请求：`{result: ContestResult}`，类型定义见下方附录。同时在`headers`里传回创建`docker`时设置的`TOKEN`。如果 `docker` 未能正常运行比赛，`ContestResult.status` 设置为 `Crashed`，不会更新分数；否则 `ContestResult.status` 设置为 `Finish`，正常更新分数。
这里不是Finished？

2024-04-29 01:57 UTC, BlitherBoom812 commented on docs/contest.md
> +  - 请求：`{result: ContestResult}`，类型定义见下方附录。同时在`headers`里传回创建`docker`时设置的`TOKEN`。如果 `docker` 未能正常运行比赛，`ContestResult.status` 设置为 `Crashed`，不会更新分数；否则 `ContestResult.status` 设置为 `Finish`，正常更新分数。
还真是

2024-04-29 04:40 UTC, xiangmy21 approved these changes

2024-04-29 04:40 UTC, merged